// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SztukaNaWidoku.Database;

#nullable disable

namespace SztukaNaWidoku.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("SztukaNaWidoku.Database.Entities.Exhibition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MuseoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MuseoId");

                    b.ToTable("Exhibitions");
                });

            modelBuilder.Entity("SztukaNaWidoku.Database.Entities.Museo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Museos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Warszawa",
                            Name = "Muzeum Narodowe w Warszawie"
                        },
                        new
                        {
                            Id = 2,
                            City = "Warszawa",
                            Name = "Muzeum Sztuki Nowoczesnej w Warszawie"
                        },
                        new
                        {
                            Id = 3,
                            City = "Sopot",
                            Name = "Państwowa Galeria Sztuki w Sopocie"
                        },
                        new
                        {
                            Id = 4,
                            City = "Warszawa",
                            Name = "Centrum Sztuki Współczesnej Zamek Ujazdowski"
                        },
                        new
                        {
                            Id = 5,
                            City = "Warszawa",
                            Name = "Zachęta Narodowa Galeria Sztuki"
                        },
                        new
                        {
                            Id = 6,
                            City = "Gdańsk",
                            Name = "Muzeum Narodowe w Gdańsku"
                        },
                        new
                        {
                            Id = 7,
                            City = "Gdynia",
                            Name = "Muzeum Miasta Gdyni"
                        },
                        new
                        {
                            Id = 8,
                            City = "Gdańsk",
                            Name = "Centrum Sztuki Współczesnej Łaźnia"
                        });
                });

            modelBuilder.Entity("SztukaNaWidoku.Database.Entities.Exhibition", b =>
                {
                    b.HasOne("SztukaNaWidoku.Database.Entities.Museo", "Museo")
                        .WithMany()
                        .HasForeignKey("MuseoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museo");
                });
#pragma warning restore 612, 618
        }
    }
}
